vcs: Fail in case the input file is not available
Signed-off-by: Frank Terbeck <ft@bewatermyfriend.org>

diff --git a/bin/generate-version-h b/bin/generate-version-h
--- a/bin/generate-version-h
+++ b/bin/generate-version-h
@@ -10,6 +10,11 @@ if test "x$input" = x || test "x$output" = x; then
     exit 1
 fi
 
+if ! test -f "$input"; then
+    printf 'generate-version-h error: Input file does not exist: %s\n' "$input" >&2
+    exit 1
+fi
+
 shift 2
 
 for file in "$@"; do
